### PR TITLE
Fix english name prefix/suffix

### PR DESCRIPTION
**Pull request by slowteetoe**
The name prefix/suffix files for english were formatted incorrectly, so all options would be returned instead of choosing from one of options.

e.g. fake.MaleFullNameWithSuffix() would return 'John Smith Jr. Sr. I II III IV V MD DDS PhD DVM' instead of 'John Smith MD'

It also seems that the way esc works with this project may have changed.  When you run 'go generate' now, everything is prefixed with '_esc'.  This was causing a compile error in fake.go

### CODE REVIEW

**Comment by nvma** [comment]
@icrowley can we merge this?

**Comment by corpix** [comment]
@nvma At this time - no, it should be refactored because it doesn't follow the Go idioms about naming. I am refactoring the whole package now and it probably will be finished in 2 weeks.

**Comment by kazamatzuri** [comment]
we could really just merge this. it's been a bit more than 2 weeks ;)

**Comment by corpix** [comment]
Haha, yeah, sorry. Let it be, lets merge this

**Comment by kazamatzuri** [comment]
only problem: this is not the whole change. to also change it when it's not reading it from the files, we also need to update the compressed representation of the files. Similar to here: https://github.com/kazamatzuri/fake/commit/db3b860caf1971acb2a188ed81ab3c2afc4223e9

**Pull request merged**
